### ISSUE TITLE
>wz stats by @UsernameDiscord tag

### ISSUE THREAD

**Issue by Nixsm** [o-clube/o-clube-discord#8]
Might be useful to check the stats of the people registered.

Possible con is pinging people around so maybe we could just use that persons nametag, whoever, if they have a different name than their discord username, this might be a problem. Could just not give a single fuck and accept that people will get pinged when their stats are getting checked. :lol:

**Comment by mzaglia** [comment]
Discord.py is able to retrieve users nickname without tagging by using `utils.get(ctx.message.guild.members, name=name)`

**Comment by mzaglia** [comment]
wz cog needs to be revised all together
